name: "Build"
on:
  push:
  pull_request:
jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Nix eval cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/nix/eval-cache-*/
          key: nix-eval-cache-${{ hashFiles('**/*.nix', 'flake.lock') }}
          restore-keys: |
            nix-eval-cache-
      - name: Get packages from flake
        id: packages
        run: |
          echo -n "packages=" >> "$GITHUB_OUTPUT"
          nix flake show --json | \
            jq -c ".packages.\"x86_64-linux\" | keys" >> "$GITHUB_OUTPUT"
    outputs:  
      packages: ${{steps.packages.outputs.packages}}
  build:
    runs-on: ubuntu-latest
    needs:
      - packages
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.packages.outputs.packages) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Nix eval cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/nix/eval-cache-*/
          key: nix-eval-cache-${{ hashFiles('**/*.nix', 'flake.lock') }}
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          diagnostic-endpoint: ""
      - run: nix build .#${{ matrix.package }}
