name: "Build"
on:
  push:
  pull_request:
jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          # Custom binary that allows uploading sources
          # Built from: https://github.com/lopsided98/magic-nix-cache/commit/7d993eaabcbbdc1ef26aec52133ee19ef8ac29a9
          source-url: https://files.benwolsieffer.com/Projects/magic-nix-cache/magic-nix-cache
          diagnostic-endpoint: ""
      - name: Get packages from flake
        id: packages
        run: |
          echo -n "packages=" >> "$GITHUB_OUTPUT"
          nix flake show --debug --json | \
            jq -c ".packages.\"x86_64-linux\" | keys" >> "$GITHUB_OUTPUT"
    outputs:  
      packages: ${{steps.packages.outputs.packages}}
  build:
    runs-on: ubuntu-latest
    needs:
      - packages
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.packages.outputs.packages) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          diagnostic-endpoint: ""
      - run: nix build --debug .#${{ matrix.package }}
