name: "Build"
on:
  push:
  pull_request:
jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          # Custom binary that allows uploading sources
          # Built from: https://github.com/lopsided98/magic-nix-cache/commit/7337f0abbabe9cb4403cb53695c33e3a371d9cf1
          source-url: https://files.benwolsieffer.com/Projects/magic-nix-cache/magic-nix-cache.nar.xz
          diagnostic-endpoint: ""
      - name: Get packages from flake
        id: packages
        run: |
          echo -n "packages=" >> "$GITHUB_OUTPUT"
          nix flake show --json | \
            jq -c ".packages.\"x86_64-linux\" | keys" >> "$GITHUB_OUTPUT"
    outputs:  
      packages: ${{steps.packages.outputs.packages}}
  build:
    runs-on: ubuntu-latest
    needs:
      - packages
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.packages.outputs.packages) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          diagnostic-endpoint: ""
      - run: nix build .#${{ matrix.package }}
      - name: Get result Nix store path
        run: echo "result=$(readlink result)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.package }}
          path: ${{ env.result }}
