name: "Update"
on:
  schedule:
    - cron: "0 12 * * FRI"
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          nix flake update --commit-lock-file
          git push
