name: "Update"
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.UPDATE_GITHUB_TOKEN }}
          fetch-depth: 0
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Nix cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/nix/
          key: nix-cache-${{ hashFiles('**/*.nix', 'flake.lock') }}
          restore-keys: |
            nix-cache-
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          # Custom binary that allows uploading sources
          # Built from: https://github.com/lopsided98/magic-nix-cache/commit/7d993eaabcbbdc1ef26aec52133ee19ef8ac29a9
          source-url: https://files.benwolsieffer.com/Projects/magic-nix-cache/magic-nix-cache
          diagnostic-endpoint: ""
      - name: Configure git user
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Update flake
        run: |
          nix flake update --commit-lock-file
          git push
